const {
  PROD_PORT,
  PROD_DB_SCHEMA,
  PROD_DB_NAME,
  PROD_DB_HOST,
  PROD_DB_PASSWORD,
  PROD_DB_USERNAME,
  PROD_DB_PORT,
} = process.env;

export default {
  PORT: PROD_PORT,
  DB_PORT: PROD_DB_PORT,
  DB_NAME: PROD_DB_NAME,
  DB_USERNAME: PROD_DB_USERNAME,
  DB_HOST: PROD_DB_HOST,
  DB_PASSWORD: PROD_DB_PASSWORD,
  DB_SCHEMA: PROD_DB_SCHEMA,
};
